I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 758, in script
    show infor_sobre()
Exception: Image 'infor_sobre' does not accept attributes '()'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 758, in script
    show infor_sobre()
  File "D:\Programas\Renpy-8.2.3-sdk\renpy\ast.py", line 1113, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "D:\Programas\Renpy-8.2.3-sdk\renpy\ast.py", line 1076, in show_imspec
    renpy.config.show(name,
  File "D:\Programas\Renpy-8.2.3-sdk\renpy\exports.py", line 739, in show
    if not base.find_target() and renpy.config.missing_show:
  File "D:\Programas\Renpy-8.2.3-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "D:\Programas\Renpy-8.2.3-sdk\renpy\display\displayable.py", line 246, in _duplicate
    args.extraneous()
  File "D:\Programas\Renpy-8.2.3-sdk\renpy\display\displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'infor_sobre' does not accept attributes '()'.

Windows-10-10.0.22621 AMD64
Ren'Py 8.2.3.24061702
Aprenda Libras 1.0
Thu Aug 29 21:29:40 2024
